public class AriaPaymentDataWrapper{
             public String cc_number {get; set; }
             public String pmCVV {get; set;}
             public String accountNumber {get; set;}
             public String RoutingNumber {get ;set; }
             public String cc_expire_mm {get; set;}
             public String cc_expire_yyyy {get; set;}
             public String TokenIDWrap {get;set;}
             public String NetTermsWrap {get;set;}
             public String PaymentMethod {get; set;}
             public String AgreementID {get;set;}
      }