public with sharing class AriaContactWrapper {
    
    public String first_name {get;set;}
    public String middle_initial {get;set;}
    public String last_name {get;set;}
    
    public String company_name {get;set;}
    public String email {get;set;}
    public String birthdate {get;set;}
    
    public String address1 {get;set;}
    public String address2 {get;set;}
    public String address3 {get;set;}
    public String city {get;set;}
    public String state_prov {get;set;}
    public String country_cd {get;set;}
    public String locality {get;set;}
    public String postal_cd {get;set;}
    
    public String work_phone {get;set;}
    public String work_phone_ext {get;set;}
    public String phone {get;set;}
    public String phone_ext {get;set;}
    public String cell_phone {get;set;}
    public String fax {get;set;}
    

}